global using System.Collections.Immutable;
global using System.Globalization;
global using System.IO.Compression;
global using System.Net;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using JetBrains.Annotations;